#include "CoreEventSystem.h"
#include "GameLog.h"

CoreEventSystem::CoreEventSystem()
{
	ADD_PARAM_COUNT(CE_EDITOR_ERROR, 1);
	ADD_PARAM_COUNT(CE_EDITOR_DELETED, 1);
	ADD_PARAM_COUNT(CE_HEIGHT_MAP_DONE, 2);
	ADD_PARAM_COUNT(CE_EDITOR_ADDED, 1);
	ADD_PARAM_COUNT(CE_EDITOR_SELECTION_CHANGED, 0);
	ADD_PARAM_COUNT(CE_COMPONENT_PROPERTY_CHANGED, 6);
	ADD_PARAM_COUNT(CE_COMPONENT_PROPERTY_REFRESH, 0);
	ADD_PARAM_COUNT(CE_EDITOR_COMPONENT_DELETED, 2);
	ADD_PARAM_COUNT(CE_COMPONENT_SELECTION_CHANGED, 0);
	ADD_PARAM_COUNT(CE_COMPONENT_ADDED, 3);
	ADD_PARAM_COUNT(CE_SCENE_OPEN, 1);
	ADD_PARAM_COUNT(CE_SCENE_NEW, 1);
	ADD_PARAM_COUNT(CE_SCENE_DESTROIED, 1);
	ADD_PARAM_COUNT(CE_SCENE_MODIFIED, 2);
	ADD_PARAM_COUNT(CE_SCENE_RENAMED, 2);
	ADD_PARAM_COUNT(CE_UNDO_ENABLE_CHANGE, 1);
	ADD_PARAM_COUNT(CE_REDO_ENABLE_CHANGE, 1);
	if (mEventParamCountList.size() < CE_MAX)
	{
		GAME_ERROR("error : all events must be assigned parameter count! cur count : %d, max count : %d, ECEventSystem", mEventParamCountList.size(), CE_MAX);
	}
}