#ifndef _TX_COMPONENT_HEADER_H_
#define _TX_COMPONENT_HEADER_H_

#include "txComponentOwner.h"

#include "txComponent.h"
#include "txComponentAlpha.h"
#include "txComponentAudio.h"
#include "txComponentCollision.h"
#include "txComponentCollisionBox.h"
#include "txComponentCollisionCapsule.h"
#include "txComponentCollisionCylinder.h"
#include "txComponentCollisionPlane.h"
#include "txComponentCollisionSphere.h"
#include "txComponentDynamicMesh.h"
#include "txComponentEffect.h"
#include "txComponentMesh.h"
#include "txComponentMove.h"
#include "txComponentPhysics.h"
#include "txComponentRotate.h"
#include "txComponentRotateSpeed.h"
#include "txComponentScale.h"
#include "txComponentStaticMesh.h"
#include "txComponentTransform.h"
#include "WindowComponentAlpha.h"
#include "WindowComponentColour.h"
#include "WindowComponentHSL.h"
#include "WindowComponentMove.h"
#include "WindowComponentRotate.h"
#include "WindowComponentRotateSpeed.h"
#include "WindowComponentScale.h"
#include "WindowComponentSelffitScale.h"
#include "WindowComponentMoveRelative.h"
#include "CameraLinkerAcceleration.h"
#include "CameraLinkerFixed.h"
#include "CameraLinkerFixedTime.h"
#include "CameraLinkerSpring.h"
#include "CameraTrembling.h"

#endif