#include "CoreEventSystem.h"
#include "ECLog.h"
#include "Utility.h"

CoreEventSystem::CoreEventSystem()
{
	ADD_PARAM_COUNT(CE_LAYOUT_DESTROIED, 1);
	ADD_PARAM_COUNT(CE_LAYOUT_CLOSED, 1);
	ADD_PARAM_COUNT(CE_WINDOW_ADDED, 3);
	ADD_PARAM_COUNT(CE_SELECTION_CHANGED, 0);
	ADD_PARAM_COUNT(CE_WINDOW_RENAMED, 2);
	ADD_PARAM_COUNT(CE_LAYOUT_RENAMED, 2);
	ADD_PARAM_COUNT(CE_WINDOW_DELETED, 2);
	ADD_PARAM_COUNT(CE_LAYOUT_ADDED, 1);
	ADD_PARAM_COUNT(CE_WINDOW_PROPERTY_CHANGED, 5);
	ADD_PARAM_COUNT(CE_LAYOUT_MODIFIED, 2);
	ADD_PARAM_COUNT(CE_LAYOUT_VISIBLE_CHANGED, 2);
	ADD_PARAM_COUNT(CE_WINDOW_POS_CHANGED, 4);
	ADD_PARAM_COUNT(CE_WINDOW_PREFAB_CHANGED, 2);
	ADD_PARAM_COUNT(CE_UNDO_ENABLE_CHANGE, 1);
	ADD_PARAM_COUNT(CE_REDO_ENABLE_CHANGE, 1);
	ADD_PARAM_COUNT(CE_PREFAB_RESOURCE_CHANGED, 0);
	ADD_PARAM_COUNT(CE_TEMPLATE_RESOURCE_CHANGED, 0);
	ADD_PARAM_COUNT(CE_WINDOW_CUTED, 1);
	ADD_PARAM_COUNT(CE_TREMBLE_MODIFIED, 2);
	ADD_PARAM_COUNT(CE_LOAD_TREMBLING, 1);
	ADD_PARAM_COUNT(CE_NEW_TREMBLING, 1);
	ADD_PARAM_COUNT(CE_ADD_NODE, 1);
	ADD_PARAM_COUNT(CE_DELETE_NODE, 1);
	ADD_PARAM_COUNT(CE_SELECT_TREMBLING_NODE, 1);
	ADD_PARAM_COUNT(CE_SELECT_KEY_FRAME, 1);
	ADD_PARAM_COUNT(CE_ADD_KEY_FRAME, 1);
	ADD_PARAM_COUNT(CE_DELETE_KEY_FRAME, 1);
	ADD_PARAM_COUNT(CE_WINDOW_COMPONENT_PROPERTY_CHANGED, 6);
	ADD_PARAM_COUNT(CE_COMPONENT_SELECTION_CHANGED, 0);
	ADD_PARAM_COUNT(CE_LOAD_ACTION_TREE, 1);
	ADD_PARAM_COUNT(CE_NEW_ACTION_TREE, 1);
	ADD_PARAM_COUNT(CE_DELETE_ACTION_TREE, 1);
	ADD_PARAM_COUNT(CE_ACTION_SELECTION_CHANGED, 0);
	ADD_PARAM_COUNT(CE_ADD_ACTION, 2);
	ADD_PARAM_COUNT(CE_DELETE_ACTION, 1);
	ADD_PARAM_COUNT(CE_ACTION_TREE_MODIFIED, 2);
	ADD_PARAM_COUNT(CE_SELECT_ACTION_TREE, 1);
	ADD_PARAM_COUNT(CE_ERROR_LOG, 1);
	ADD_PARAM_COUNT(CE_INFO_LOG, 1);
	if (mEventParamCountList.size() < CE_MAX)
	{
		EDITOR_CORE_ERROR("error : all events must be assigned parameter count! cur count : %d, max count : %d", mEventParamCountList.size(), CE_MAX);
	}
}